"""
Defines the validation models used in this application.
"""
from pydantic import BaseModel

from taleboard.schema.enums import PositionCell, SizeInFrame, Orientation, ShotSize, CameraAngle


class Character(BaseModel):
    """
    Represents a character in the story, as the application stores and the user can edit.

    Attributes:
        name: str - Full name of the character.
        description: str - A brief description of the character (generated by an LLM).
        appearance_reference: str - A path/URL to a reference image. Defaults to None.
    """
    name: str
    description: str
    appearance_reference: str | None = None

class Region(BaseModel):
    """
    Represents a single character within a shot.

    Attributes:
        character_id: str - Unique identifier of the character who "owns" this region.
        position: PositionCell - Position of the region in the 3x3 grid.
        size: SizeInFrame - Size of the region in the frame.
        orientation: Orientation - Orientation of the generated character in the frame.
        action: str - Action being performed by the character -- renders as a pose.
    """
    character_id: str
    position: PositionCell
    size: SizeInFrame
    orientation: Orientation
    action: str

class Shot(BaseModel):
    """
    Represents one storyboard panel.

    Attributes:
        description: str - A brief description of what happens in the shot.
        setting: str - A brief description of the "background" of the shot.
        regions: list[Region] - A list of character regions within the shot.
        paragraph_index: int - Identifies uniquely the paragraph from which this shot originated.
        shot_size: ShotSize - Framing of the shot.
        angle: CameraAngle - Camera angle of the shot.
        duration_s: float - Duration that the shot lasts for (in seconds).
        generated_frame: str - A path or URL to the generated shot image. Defaults to None.
        needs_review: bool - A review flag. If set True, a human needs to manually review this shot. Defaults to False -- we don't want a human to review a shot unless there is an error in parsing/rendering.
    """
    description: str
    setting: str
    regions: list[Region]
    paragraph_index: int
    shot_size: ShotSize
    angle: CameraAngle
    duration_s: float
    generated_frame: str | None = None
    needs_review: bool = False


class Project(BaseModel):
    """
    Represents a full storyboard project.
    
    Attributes:
        title: str - A title for the project.
        shots: list[Shot] - A list of shots that are in the project.
        cast: dict[str,Character] - A mapping between each unique character ID and each character.
    """
    title: str
    shots: list[Shot]
    cast: dict[str, Character]